# version: '3.8'
# services:
#   nginx:
#     build: 
#       context: .
#     ports:
#       - 9000:9000
#     volumes:
#       - ../web/build:/usr/share/nginx/html
#       - ./default.conf:/etc/nginx/conf.d/default.conf

#       #docker compose -p app-chat up -d (Lệnh để build lên docker)

# ------v2
# version: '3.8'

# services:
#   client:
#     build: ../job-fe  # Đường dẫn đến thư mục job-fe
#     ports:
#       - "3000:80"  # Mở cổng 80 của container ra ngoài cổng 3000
#     volumes:
#       - ../job-fe/build:/usr/share/nginx/html  # Liên kết thư mục build của React với thư mục HTML của Nginx
#     networks:
#       - job-portal-network

#   nginx:
#     image: nginx:alpine
#     volumes:
#       - ./default.conf:/etc/nginx/conf.d/default.conf  # Sử dụng tệp cấu hình Nginx
#     ports:
#       - "80:80"  # Cổng phục vụ ứng dụng
#     networks:
#       - job-portal-network

# networks:
#   job-portal-network:
#     driver: bridge

# ------v3
# version: '3.8'
# services:
#   nginx:
#     build:
#       context: .
#     ports:
#       - "3000:80"
#     volumes:
#       - ../job-fe/build:/usr/share/nginx/html
#       - ./default.conf:/etc/nginx/conf.d/default.conf

# ------v4
version: '3.8'

services:
  frontend:
    build:
      context: ../front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ../back-end
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - ../back-end/.env

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
